/**
 * This class is generated by jOOQ
 */
package com.songspk.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Albums extends org.jooq.impl.TableImpl<com.songspk.tables.records.AlbumsRecord> {

	private static final long serialVersionUID = 833664838;

	/**
	 * The singleton instance of <code>public.albums</code>
	 */
	public static final com.songspk.tables.Albums ALBUMS = new com.songspk.tables.Albums();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.songspk.tables.records.AlbumsRecord> getRecordType() {
		return com.songspk.tables.records.AlbumsRecord.class;
	}

	/**
	 * The column <code>public.albums.movie</code>.
	 */
	public final org.jooq.TableField<com.songspk.tables.records.AlbumsRecord, java.lang.String> MOVIE = createField("movie", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.albums.link</code>.
	 */
	public final org.jooq.TableField<com.songspk.tables.records.AlbumsRecord, java.lang.String> LINK = createField("link", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.albums.is_fetched</code>.
	 */
	public final org.jooq.TableField<com.songspk.tables.records.AlbumsRecord, java.lang.Boolean> IS_FETCHED = createField("is_fetched", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>public.albums.released</code>.
	 */
	public final org.jooq.TableField<com.songspk.tables.records.AlbumsRecord, java.lang.String> RELEASED = createField("released", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.albums.cast</code>.
	 */
	public final org.jooq.TableField<com.songspk.tables.records.AlbumsRecord, java.lang.String> CAST = createField("cast", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>public.albums.director</code>.
	 */
	public final org.jooq.TableField<com.songspk.tables.records.AlbumsRecord, java.lang.String> DIRECTOR = createField("director", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.albums.id</code>.
	 */
	public final org.jooq.TableField<com.songspk.tables.records.AlbumsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.albums</code> table reference
	 */
	public Albums() {
		this("albums", null);
	}

	/**
	 * Create an aliased <code>public.albums</code> table reference
	 */
	public Albums(java.lang.String alias) {
		this(alias, com.songspk.tables.Albums.ALBUMS);
	}

	private Albums(java.lang.String alias, org.jooq.Table<com.songspk.tables.records.AlbumsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Albums(java.lang.String alias, org.jooq.Table<com.songspk.tables.records.AlbumsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.songspk.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.songspk.tables.records.AlbumsRecord, java.lang.Long> getIdentity() {
		return com.songspk.Keys.IDENTITY_ALBUMS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.songspk.tables.records.AlbumsRecord> getPrimaryKey() {
		return com.songspk.Keys.ALBUMS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.songspk.tables.records.AlbumsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.songspk.tables.records.AlbumsRecord>>asList(com.songspk.Keys.ALBUMS_LINK_KEY, com.songspk.Keys.ALBUMS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.songspk.tables.Albums as(java.lang.String alias) {
		return new com.songspk.tables.Albums(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.songspk.tables.Albums rename(java.lang.String name) {
		return new com.songspk.tables.Albums(name, null);
	}
}
