/**
 * This class is generated by jOOQ
 */
package com.songspk;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.albums_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> ALBUMS_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("albums_id_seq", com.songspk.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.songs_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SONGS_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("songs_id_seq", com.songspk.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
