/**
 * This class is generated by jOOQ
 */
package com.songspk;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.albums
	 */
	public static final com.songspk.tables.Albums ALBUMS = com.songspk.tables.Albums.ALBUMS;

	/**
	 * The table public.songs
	 */
	public static final com.songspk.tables.Songs SONGS = com.songspk.tables.Songs.SONGS;
}
